name: Test-Project
on:
  push:
    branches:
      - main
      - 'dev-/feature/**'
  workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Git checkout
              uses: actions/checkout@v3
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install Dependencies
              run: npm ci
            - name: Run Tests
              run: npm test

    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps: 
            - name: Git checkout
              uses: actions/checkout@v3
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install Dependencies
              run: npm ci

            - name: Build Project
              run: npm run build
            - name: Deploy to GitHub Pages
              run : echo "${{ toJSON(github) }}"

            - name: upload
              uses: actions/upload-artifact@v3
              with:
                  name: dist
                  path: |
                      dist
                      index.html
                      package.json

